services:
  frontend:
    build: ./client
    hostname: frontend
    environment:
      - VUE_APP_CONFIG_URL=http://api.localhost/
    ports:
      - 8080:8080

  backend:
    build: ./content
    hostname: backend
    ports:
      - 5000:5000

  reverse:
    build: ./reverseproxy
    ports:
      - 80:80